name: codecov

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: make lib_tests_run

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          working-directory: ./lib/my
          gcov: true
          token: ${{ secrets.CODECOV_TOKEN }}

